name: Build RandomSpawnPlus5

on: [ push ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "github.actor != 'dependabot[bot]'"
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew clean build

      - name: Release RandomSpawnPlus5
        if: github.ref_name == 'master'
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "RandomSpawnPlus5 v5.1.0-SNAPSHOT"
          automatic_release_tag: "5.1.0-SNAPSHOT"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "build/libs/*.jar"
          prerelease: true
